version: 2.1

orbs:
  python: circleci/python@0.3.2
  aws-cli: circleci/aws-cli@1.2.1

jobs:
  build-and-test:
    executor:
      name: python/default
      tag: "3.7"
    steps:
      - checkout
      - run:
          name: Setup Virtual env
          command: |
            virtualenv -p python3.7 env
            echo "source ./env/bin/activate" >> $BASH_ENV
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Create ENV file
          command: env > .env
      - run:
          name: Test
          command: pytest
      - run:
          name: Create Zipfile archive of Dependencies
          command: |
            cd env/lib/python3.7/site-packages
            zip -r9 ../../../../function.zip .
      - run:
          name: Add App to Zipfile
          command: zip -g ./function.zip .env -r app
      - persist_to_workspace:
          root: .
          paths:
            - function.zip

  deploy-dev:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: ./
      - aws-cli/setup:
          aws-region: us-east-2
          aws-access-key-id: AKIASTF3EA4YIF6YAUNH
          aws-secret-access-key: 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
      - run:
          name: Upload to S3
          command: aws s3 cp function.zip s3://hqkim/function.zip
      - run:
          name: Deploy new Lambda
          command: aws lambda update-function-code --function-name fastapihqkim --s3-bucket hqkim --s3-key function.zip

workflows:
  build-test-and-deploy:
    jobs:
      - build-and-test:
          context: tdd_lab_test
          filters:
            branches:
              only:
                - main
      - deploy-dev:
          context: tdd_lab_test
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main
